version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: 'gitlab.eamile.com'  # replace on your domain or ip
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.eamile.com'  # replace on your url
# Uncomment for HTTPS (див. далі)
#        letsencrypt['enable'] = true
#        letsencrypt['contact_emails'] = ['info@example.com']
#        letsencrypt['auto_renew'] = true
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
      - "2222:22"  # SSH (changed from 22 to avoid conflicts if necessary)
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab